logging:
  level:
    root: INFO
    web: INFO
server:
  connection-timeout: 3600s
  port: 7777
  tomcat:
    accept-count: 100
    max-connections: 8192
    threads:
      min-spare: 1
      max: 1
spring:
  mvc:
    async:
      request-timeout: 3600000
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
